# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: termination_handler_params_msg.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n$termination_handler_params_msg.proto\"l\n ContactTerminationHandlerMessage\x12\x13\n\x0b\x62uffer_time\x18\x01 \x02(\x01\x12\x18\n\x10\x66orce_thresholds\x18\x02 \x03(\x01\x12\x19\n\x11torque_thresholds\x18\x03 \x03(\x01\"F\n\x15JointThresholdMessage\x12\x13\n\x0b\x62uffer_time\x18\x01 \x02(\x01\x12\x18\n\x10joint_thresholds\x18\x02 \x03(\x01\"h\n\x14PoseThresholdMessage\x12\x13\n\x0b\x62uffer_time\x18\x01 \x02(\x01\x12\x1b\n\x13position_thresholds\x18\x02 \x03(\x01\x12\x1e\n\x16orientation_thresholds\x18\x03 \x03(\x01\"4\n\x1dTimeTerminationHandlerMessage\x12\x13\n\x0b\x62uffer_time\x18\x01 \x02(\x01')



_CONTACTTERMINATIONHANDLERMESSAGE = DESCRIPTOR.message_types_by_name['ContactTerminationHandlerMessage']
_JOINTTHRESHOLDMESSAGE = DESCRIPTOR.message_types_by_name['JointThresholdMessage']
_POSETHRESHOLDMESSAGE = DESCRIPTOR.message_types_by_name['PoseThresholdMessage']
_TIMETERMINATIONHANDLERMESSAGE = DESCRIPTOR.message_types_by_name['TimeTerminationHandlerMessage']
ContactTerminationHandlerMessage = _reflection.GeneratedProtocolMessageType('ContactTerminationHandlerMessage', (_message.Message,), {
  'DESCRIPTOR' : _CONTACTTERMINATIONHANDLERMESSAGE,
  '__module__' : 'termination_handler_params_msg_pb2'
  # @@protoc_insertion_point(class_scope:ContactTerminationHandlerMessage)
  })
_sym_db.RegisterMessage(ContactTerminationHandlerMessage)

JointThresholdMessage = _reflection.GeneratedProtocolMessageType('JointThresholdMessage', (_message.Message,), {
  'DESCRIPTOR' : _JOINTTHRESHOLDMESSAGE,
  '__module__' : 'termination_handler_params_msg_pb2'
  # @@protoc_insertion_point(class_scope:JointThresholdMessage)
  })
_sym_db.RegisterMessage(JointThresholdMessage)

PoseThresholdMessage = _reflection.GeneratedProtocolMessageType('PoseThresholdMessage', (_message.Message,), {
  'DESCRIPTOR' : _POSETHRESHOLDMESSAGE,
  '__module__' : 'termination_handler_params_msg_pb2'
  # @@protoc_insertion_point(class_scope:PoseThresholdMessage)
  })
_sym_db.RegisterMessage(PoseThresholdMessage)

TimeTerminationHandlerMessage = _reflection.GeneratedProtocolMessageType('TimeTerminationHandlerMessage', (_message.Message,), {
  'DESCRIPTOR' : _TIMETERMINATIONHANDLERMESSAGE,
  '__module__' : 'termination_handler_params_msg_pb2'
  # @@protoc_insertion_point(class_scope:TimeTerminationHandlerMessage)
  })
_sym_db.RegisterMessage(TimeTerminationHandlerMessage)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CONTACTTERMINATIONHANDLERMESSAGE._serialized_start=40
  _CONTACTTERMINATIONHANDLERMESSAGE._serialized_end=148
  _JOINTTHRESHOLDMESSAGE._serialized_start=150
  _JOINTTHRESHOLDMESSAGE._serialized_end=220
  _POSETHRESHOLDMESSAGE._serialized_start=222
  _POSETHRESHOLDMESSAGE._serialized_end=326
  _TIMETERMINATIONHANDLERMESSAGE._serialized_start=328
  _TIMETERMINATIONHANDLERMESSAGE._serialized_end=380
# @@protoc_insertion_point(module_scope)
